name: Tests and linters
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest
      - name: Run mypy
        run: mypy src/
      - name: Run black
        run: black --line-length=79 --diff --check src/
      - name: Run isort
        run: isort --check-only src/
      - name: Run flake8
        run: flake8 src/